# Generated by Django 3.2.18 on 2023-03-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static/item_images'),
        ),
    ]
